// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService 暴露账号管理能力给前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * Create 校验连通性后创建账号，返回脱敏账号。
 */
export function Create(payload: model$0.ProviderConfig): $CancellablePromise<model$0.Account> {
    return $Call.ByID(3160809237, payload).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Delete 删除账号。
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(735440914, id);
}

/**
 * List 返回所有账号（密钥已脱敏）。
 */
export function List(): $CancellablePromise<model$0.Account[]> {
    return $Call.ByID(2448579993).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Update 更新账号；空密钥表示沿用原密钥。
 */
export function Update(id: string, payload: model$0.ProviderConfig): $CancellablePromise<model$0.Account> {
    return $Call.ByID(3536380204, id, payload).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Account.createFrom;
const $$createType1 = $Create.Array($$createType0);
