// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BucketService 暴露存储桶与对象列举能力给前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * ListBuckets 列出指定账号下的所有桶。
 */
export function ListBuckets(provider: string, accountID: string): $CancellablePromise<model$0.BucketInfo[]> {
    return $Call.ByID(3058152933, provider, accountID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListDomains 返回桶绑定的 CDN 域名（provider 不支持 CDN 时返回空切片）。
 */
export function ListDomains(accountID: string, bucket: string): $CancellablePromise<string[]> {
    return $Call.ByID(2963180175, accountID, bucket).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListObjects 列出桶内对象（支持前缀/分页）。
 */
export function ListObjects(params: model$0.ListParams): $CancellablePromise<model$0.ListResult> {
    return $Call.ByID(2735977598, params).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.BucketInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = model$0.ListResult.createFrom;
