// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CDNService 暴露 CDN 刷新/预热/配额能力给前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * Prefetch 预热 CDN。Provider 不支持 CDN 时返回错误。
 */
export function Prefetch(accountID: string, urls: string[]): $CancellablePromise<void> {
    return $Call.ByID(446996050, accountID, urls);
}

/**
 * Quota 查询 CDN 刷新/预热每日配额，失败返回 nil（前端容错）。
 */
export function Quota(accountID: string): $CancellablePromise<model$0.CDNQuota | null> {
    return $Call.ByID(1400626611, accountID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Refresh 刷新 CDN 缓存。Provider 不支持 CDN 时静默成功（与原 handler 行为一致）。
 */
export function Refresh(accountID: string, urls: string[]): $CancellablePromise<void> {
    return $Call.ByID(2444046908, accountID, urls);
}

// Private type creation functions
const $$createType0 = model$0.CDNQuota.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
