// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GovernanceService 暴露存储桶治理能力（生命周期/CORS/防盗链/加密/版本控制）给前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteLifecycle 删除存储桶生命周期规则。
 */
export function DeleteLifecycle(accountID: string, bucket: string): $CancellablePromise<void> {
    return $Call.ByID(1343245665, accountID, bucket);
}

/**
 * GetCORS 查询存储桶 CORS 跨域规则。
 */
export function GetCORS(accountID: string, bucket: string): $CancellablePromise<model$0.CORSRule[]> {
    return $Call.ByID(2255993737, accountID, bucket).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetEncryption 查询存储桶加密配置。
 */
export function GetEncryption(accountID: string, bucket: string): $CancellablePromise<model$0.EncryptionConfig> {
    return $Call.ByID(2575883433, accountID, bucket).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLifecycle 查询存储桶生命周期规则。
 */
export function GetLifecycle(accountID: string, bucket: string): $CancellablePromise<model$0.LifecycleRule[]> {
    return $Call.ByID(2900647260, accountID, bucket).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetReferer 查询存储桶防盗链配置。
 */
export function GetReferer(accountID: string, bucket: string): $CancellablePromise<model$0.RefererConfig> {
    return $Call.ByID(683353961, accountID, bucket).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetVersioning 查询存储桶版本控制状态，返回 "Enabled"/"Suspended"/""。
 */
export function GetVersioning(accountID: string, bucket: string): $CancellablePromise<string> {
    return $Call.ByID(2274468124, accountID, bucket);
}

/**
 * ListObjectVersions 查询对象历史版本列表。
 */
export function ListObjectVersions(p: model$0.VersionListParams): $CancellablePromise<model$0.VersionList | null> {
    return $Call.ByID(452465218, p).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * PutCORS 设置存储桶 CORS 跨域规则。
 */
export function PutCORS(p: $models.CORSPayload): $CancellablePromise<void> {
    return $Call.ByID(542059260, p);
}

/**
 * PutEncryption 设置存储桶加密配置。
 */
export function PutEncryption(p: $models.EncryptionPayload): $CancellablePromise<void> {
    return $Call.ByID(1755932132, p);
}

/**
 * PutLifecycle 设置存储桶生命周期规则。
 */
export function PutLifecycle(p: $models.LifecyclePayload): $CancellablePromise<void> {
    return $Call.ByID(1087995607, p);
}

/**
 * PutReferer 设置存储桶防盗链配置。
 */
export function PutReferer(p: $models.RefererPayload): $CancellablePromise<void> {
    return $Call.ByID(1321331502, p);
}

/**
 * PutVersioning 设置存储桶版本控制状态，status 为 "Enabled" 时开启，否则挂起。
 */
export function PutVersioning(accountID: string, bucket: string, status: string): $CancellablePromise<void> {
    return $Call.ByID(4121936841, accountID, bucket, status);
}

// Private type creation functions
const $$createType0 = model$0.CORSRule.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.EncryptionConfig.createFrom;
const $$createType3 = model$0.LifecycleRule.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.RefererConfig.createFrom;
const $$createType6 = model$0.VersionList.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
