// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * CORSPayload CORS 规则写入入参。
 */
export class CORSPayload {
    /**
     * 账号 ID
     */
    "accountId": string;

    /**
     * 存储桶名
     */
    "bucket": string;

    /**
     * CORS 规则集
     */
    "rules": model$0.CORSRule[];

    /** Creates a new CORSPayload instance. */
    constructor($$source: Partial<CORSPayload> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("rules" in $$source)) {
            this["rules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CORSPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): CORSPayload {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField2_0($$parsedSource["rules"]);
        }
        return new CORSPayload($$parsedSource as Partial<CORSPayload>);
    }
}

/**
 * EncryptionPayload 加密配置写入入参。
 */
export class EncryptionPayload {
    /**
     * 账号 ID
     */
    "accountId": string;

    /**
     * 存储桶名
     */
    "bucket": string;

    /**
     * 加密配置
     */
    "config": model$0.EncryptionConfig;

    /** Creates a new EncryptionPayload instance. */
    constructor($$source: Partial<EncryptionPayload> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new model$0.EncryptionConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncryptionPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): EncryptionPayload {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new EncryptionPayload($$parsedSource as Partial<EncryptionPayload>);
    }
}

/**
 * LifecyclePayload 生命周期规则写入入参。
 */
export class LifecyclePayload {
    /**
     * 账号 ID
     */
    "accountId": string;

    /**
     * 存储桶名
     */
    "bucket": string;

    /**
     * 生命周期规则集
     */
    "rules": model$0.LifecycleRule[];

    /** Creates a new LifecyclePayload instance. */
    constructor($$source: Partial<LifecyclePayload> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("rules" in $$source)) {
            this["rules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LifecyclePayload instance from a string or object.
     */
    static createFrom($$source: any = {}): LifecyclePayload {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField2_0($$parsedSource["rules"]);
        }
        return new LifecyclePayload($$parsedSource as Partial<LifecyclePayload>);
    }
}

/**
 * RefererPayload 防盗链配置写入入参。
 */
export class RefererPayload {
    /**
     * 账号 ID
     */
    "accountId": string;

    /**
     * 存储桶名
     */
    "bucket": string;

    /**
     * 防盗链配置
     */
    "config": model$0.RefererConfig;

    /** Creates a new RefererPayload instance. */
    constructor($$source: Partial<RefererPayload> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new model$0.RefererConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefererPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): RefererPayload {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new RefererPayload($$parsedSource as Partial<RefererPayload>);
    }
}

/**
 * TransferRef 标识一个已入队的传输任务。
 */
export class TransferRef {
    /**
     * 入队后生成的传输任务 ID
     */
    "transferId": string;

    /** Creates a new TransferRef instance. */
    constructor($$source: Partial<TransferRef> = {}) {
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferRef instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferRef($$parsedSource as Partial<TransferRef>);
    }
}

/**
 * URLResult 为生成的对象访问/签名 URL。
 */
export class URLResult {
    /**
     * 生成的 URL
     */
    "url": string;

    /** Creates a new URLResult instance. */
    constructor($$source: Partial<URLResult> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new URLResult instance from a string or object.
     */
    static createFrom($$source: any = {}): URLResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new URLResult($$parsedSource as Partial<URLResult>);
    }
}

// Private type creation functions
const $$createType0 = model$0.CORSRule.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.EncryptionConfig.createFrom;
const $$createType3 = model$0.LifecycleRule.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.RefererConfig.createFrom;
