// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ObjectService 暴露对象上传/下载/管理能力给前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFolder 在对象存储中创建文件夹（以 / 结尾的空对象）。
 */
export function CreateFolder(accountID: string, bucket: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(3159339607, accountID, bucket, key);
}

/**
 * Delete 批量删除对象。
 */
export function Delete(accountID: string, bucket: string, keys: string[]): $CancellablePromise<void> {
    return $Call.ByID(1628198016, accountID, bucket, keys);
}

/**
 * Download 入队一个下载任务，返回传输任务引用。
 */
export function Download(p: model$0.DownloadParams): $CancellablePromise<$models.TransferRef> {
    return $Call.ByID(2546209527, p).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Fetch 入队一个 URL 抓取上传任务，返回传输任务引用。
 */
export function Fetch(p: model$0.UploadParams): $CancellablePromise<$models.TransferRef> {
    return $Call.ByID(2301933869, p).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GenerateURL 生成对象的访问/签名 URL。
 */
export function GenerateURL(p: model$0.SignedURLParams): $CancellablePromise<$models.URLResult> {
    return $Call.ByID(809099845, p).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Rename 重命名对象。
 */
export function Rename(p: model$0.RenameParams): $CancellablePromise<void> {
    return $Call.ByID(403859481, p);
}

/**
 * Upload 入队一个上传任务，返回传输任务引用。
 */
export function Upload(p: model$0.UploadParams): $CancellablePromise<$models.TransferRef> {
    return $Call.ByID(4262426742, p).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TransferRef.createFrom;
const $$createType1 = $models.URLResult.createFrom;
