// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 暴露应用设置与 provider 功能查询能力给前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * Get 返回应用设置。
 */
export function Get(): $CancellablePromise<model$0.AppSettings> {
    return $Call.ByID(4277422007).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ProviderFeatures 返回指定账号对应 provider 的功能列表。
 */
export function ProviderFeatures(accountID: string): $CancellablePromise<string[]> {
    return $Call.ByID(1228298715, accountID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Update 更新并返回应用设置，空字段回退为默认值。
 */
export function Update(settings: model$0.AppSettings): $CancellablePromise<model$0.AppSettings> {
    return $Call.ByID(376229460, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.AppSettings.createFrom;
const $$createType1 = $Create.Array($Create.Any);
