// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService 暴露原生系统能力（对话框、剪贴板、剪贴板图片）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenFileDialog 打开多选文件对话框，返回选中路径。
 */
export function OpenFileDialog(): $CancellablePromise<string[]> {
    return $Call.ByID(1231704119).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenFolderDialog 打开文件夹选择对话框，返回选中目录（单元素切片）。
 */
export function OpenFolderDialog(): $CancellablePromise<string[]> {
    return $Call.ByID(1406730153).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReadClipboardImage 读取剪贴板图片存临时 PNG，返回路径。
 */
export function ReadClipboardImage(): $CancellablePromise<string> {
    return $Call.ByID(3357403826);
}

/**
 * WriteClipboardText 写入文本到剪贴板。
 */
export function WriteClipboardText(text: string): $CancellablePromise<void> {
    return $Call.ByID(1049659365, text);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
