// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransferService 暴露传输任务管理能力给前端绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * Cancel 取消指定传输任务。
 */
export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(4085967437, id);
}

/**
 * List 返回所有传输任务。
 */
export function List(): $CancellablePromise<model$0.TransferTask[]> {
    return $Call.ByID(1087212723).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.TransferTask.createFrom;
const $$createType1 = $Create.Array($$createType0);
