// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Account 账户实体。
 */
export class Account {
    "id": string;
    "provider": string;
    "name": string;
    "accessKey": string;
    "secretKey"?: string;
    "endpoint"?: string;
    "region"?: string;
    "serviceName"?: string;
    "internal": boolean;
    "paging": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("internal" in $$source)) {
            this["internal"] = false;
        }
        if (!("paging" in $$source)) {
            this["paging"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account($$parsedSource as Partial<Account>);
    }
}

/**
 * AppSettings 应用设置。
 */
export class AppSettings {
    "language": string;
    "theme": string;
    "https": boolean;
    "hideDeleteButton": boolean;
    "paging": boolean;
    "copyType": string;
    "autoRefreshCDN": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("https" in $$source)) {
            this["https"] = false;
        }
        if (!("hideDeleteButton" in $$source)) {
            this["hideDeleteButton"] = false;
        }
        if (!("paging" in $$source)) {
            this["paging"] = false;
        }
        if (!("copyType" in $$source)) {
            this["copyType"] = "";
        }
        if (!("autoRefreshCDN" in $$source)) {
            this["autoRefreshCDN"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * BucketInfo 存储桶元信息。
 */
export class BucketInfo {
    "name": string;
    "location"?: string;
    "provider": string;

    /** Creates a new BucketInfo instance. */
    constructor($$source: Partial<BucketInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BucketInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BucketInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BucketInfo($$parsedSource as Partial<BucketInfo>);
    }
}

/**
 * CDNQuota CDN 刷新/预热每日配额。
 */
export class CDNQuota {
    "urlRefreshRemain": number;
    "urlRefreshLimit": number;
    "dirRefreshRemain": number;
    "dirRefreshLimit": number;
    "prefetchRemain": number;
    "prefetchLimit": number;

    /** Creates a new CDNQuota instance. */
    constructor($$source: Partial<CDNQuota> = {}) {
        if (!("urlRefreshRemain" in $$source)) {
            this["urlRefreshRemain"] = 0;
        }
        if (!("urlRefreshLimit" in $$source)) {
            this["urlRefreshLimit"] = 0;
        }
        if (!("dirRefreshRemain" in $$source)) {
            this["dirRefreshRemain"] = 0;
        }
        if (!("dirRefreshLimit" in $$source)) {
            this["dirRefreshLimit"] = 0;
        }
        if (!("prefetchRemain" in $$source)) {
            this["prefetchRemain"] = 0;
        }
        if (!("prefetchLimit" in $$source)) {
            this["prefetchLimit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CDNQuota instance from a string or object.
     */
    static createFrom($$source: any = {}): CDNQuota {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CDNQuota($$parsedSource as Partial<CDNQuota>);
    }
}

/**
 * CORSRule CORS 跨域规则。
 */
export class CORSRule {
    "allowedOrigins": string[];
    "allowedMethods": string[];
    "allowedHeaders": string[];
    "exposeHeaders"?: string[];
    "maxAgeSeconds": number;

    /** Creates a new CORSRule instance. */
    constructor($$source: Partial<CORSRule> = {}) {
        if (!("allowedOrigins" in $$source)) {
            this["allowedOrigins"] = [];
        }
        if (!("allowedMethods" in $$source)) {
            this["allowedMethods"] = [];
        }
        if (!("allowedHeaders" in $$source)) {
            this["allowedHeaders"] = [];
        }
        if (!("maxAgeSeconds" in $$source)) {
            this["maxAgeSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CORSRule instance from a string or object.
     */
    static createFrom($$source: any = {}): CORSRule {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedOrigins" in $$parsedSource) {
            $$parsedSource["allowedOrigins"] = $$createField0_0($$parsedSource["allowedOrigins"]);
        }
        if ("allowedMethods" in $$parsedSource) {
            $$parsedSource["allowedMethods"] = $$createField1_0($$parsedSource["allowedMethods"]);
        }
        if ("allowedHeaders" in $$parsedSource) {
            $$parsedSource["allowedHeaders"] = $$createField2_0($$parsedSource["allowedHeaders"]);
        }
        if ("exposeHeaders" in $$parsedSource) {
            $$parsedSource["exposeHeaders"] = $$createField3_0($$parsedSource["exposeHeaders"]);
        }
        return new CORSRule($$parsedSource as Partial<CORSRule>);
    }
}

/**
 * DeleteMarker 删除标记。
 */
export class DeleteMarker {
    "key": string;
    "versionId": string;
    "isLatest": boolean;
    "lastModified": string;

    /** Creates a new DeleteMarker instance. */
    constructor($$source: Partial<DeleteMarker> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("versionId" in $$source)) {
            this["versionId"] = "";
        }
        if (!("isLatest" in $$source)) {
            this["isLatest"] = false;
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteMarker instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteMarker {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteMarker($$parsedSource as Partial<DeleteMarker>);
    }
}

/**
 * DownloadParams 下载参数。
 */
export class DownloadParams {
    "accountId": string;
    "bucket": string;
    "key": string;
    "localPath": string;

    /** Creates a new DownloadParams instance. */
    constructor($$source: Partial<DownloadParams> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadParams($$parsedSource as Partial<DownloadParams>);
    }
}

/**
 * EncryptionConfig 服务端加密配置。
 */
export class EncryptionConfig {
    "enabled": boolean;

    /**
     * "AES256" | "aws:kms"
     */
    "algorithm": string;
    "kmsKeyId"?: string;

    /** Creates a new EncryptionConfig instance. */
    constructor($$source: Partial<EncryptionConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("algorithm" in $$source)) {
            this["algorithm"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncryptionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): EncryptionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EncryptionConfig($$parsedSource as Partial<EncryptionConfig>);
    }
}

/**
 * LifecycleRule 生命周期规则。
 */
export class LifecycleRule {
    "id": string;
    "prefix": string;
    "enabled": boolean;

    /**
     * 过期天数，0 表示不删除
     */
    "expiration": number;
    "transition"?: LifecycleTransition | null;

    /** Creates a new LifecycleRule instance. */
    constructor($$source: Partial<LifecycleRule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("expiration" in $$source)) {
            this["expiration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LifecycleRule instance from a string or object.
     */
    static createFrom($$source: any = {}): LifecycleRule {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transition" in $$parsedSource) {
            $$parsedSource["transition"] = $$createField4_0($$parsedSource["transition"]);
        }
        return new LifecycleRule($$parsedSource as Partial<LifecycleRule>);
    }
}

/**
 * LifecycleTransition 存储类型迁移规则。
 */
export class LifecycleTransition {
    "days": number;
    "storageClass": string;

    /** Creates a new LifecycleTransition instance. */
    constructor($$source: Partial<LifecycleTransition> = {}) {
        if (!("days" in $$source)) {
            this["days"] = 0;
        }
        if (!("storageClass" in $$source)) {
            this["storageClass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LifecycleTransition instance from a string or object.
     */
    static createFrom($$source: any = {}): LifecycleTransition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LifecycleTransition($$parsedSource as Partial<LifecycleTransition>);
    }
}

/**
 * ListParams 列表请求参数。
 */
export class ListParams {
    "accountId": string;
    "bucket": string;
    "prefix": string;
    "marker": string;
    "limit": number;
    "delimiter": string;

    /** Creates a new ListParams instance. */
    constructor($$source: Partial<ListParams> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("marker" in $$source)) {
            this["marker"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("delimiter" in $$source)) {
            this["delimiter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ListParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListParams($$parsedSource as Partial<ListParams>);
    }
}

/**
 * ListResult 对象列表返回结果。
 */
export class ListResult {
    "items": ObjectItem[];
    "marker"?: string;
    "truncated": boolean;

    /** Creates a new ListResult instance. */
    constructor($$source: Partial<ListResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ListResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ListResult($$parsedSource as Partial<ListResult>);
    }
}

/**
 * ObjectItem 对象条目。
 */
export class ObjectItem {
    "key": string;
    "size": number;
    "mimeType"?: string;
    "etag"?: string;
    "lastModified"?: string;
    "isDir"?: boolean;

    /** Creates a new ObjectItem instance. */
    constructor($$source: Partial<ObjectItem> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ObjectItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectItem($$parsedSource as Partial<ObjectItem>);
    }
}

/**
 * ObjectVersion 对象版本信息。
 */
export class ObjectVersion {
    "key": string;
    "versionId": string;
    "isLatest": boolean;
    "size": number;
    "lastModified": string;
    "storageClass"?: string;

    /** Creates a new ObjectVersion instance. */
    constructor($$source: Partial<ObjectVersion> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("versionId" in $$source)) {
            this["versionId"] = "";
        }
        if (!("isLatest" in $$source)) {
            this["isLatest"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): ObjectVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectVersion($$parsedSource as Partial<ObjectVersion>);
    }
}

/**
 * ProviderConfig 账户凭证配置。
 */
export class ProviderConfig {
    "provider": string;
    "name": string;
    "accessKey": string;
    "secretKey": string;
    "endpoint"?: string;
    "region"?: string;
    "serviceName"?: string;
    "internal": boolean;
    "paging": boolean;

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }
        if (!("internal" in $$source)) {
            this["internal"] = false;
        }
        if (!("paging" in $$source)) {
            this["paging"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

/**
 * RefererConfig 防盗链配置。
 */
export class RefererConfig {
    "enabled": boolean;

    /**
     * "whitelist" | "blacklist"
     */
    "type": string;
    "allowEmpty": boolean;
    "referers": string[];

    /** Creates a new RefererConfig instance. */
    constructor($$source: Partial<RefererConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("allowEmpty" in $$source)) {
            this["allowEmpty"] = false;
        }
        if (!("referers" in $$source)) {
            this["referers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefererConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): RefererConfig {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("referers" in $$parsedSource) {
            $$parsedSource["referers"] = $$createField3_0($$parsedSource["referers"]);
        }
        return new RefererConfig($$parsedSource as Partial<RefererConfig>);
    }
}

/**
 * RenameParams 重命名参数。
 */
export class RenameParams {
    "accountId": string;
    "bucket": string;
    "from": string;
    "to": string;

    /** Creates a new RenameParams instance. */
    constructor($$source: Partial<RenameParams> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameParams instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameParams($$parsedSource as Partial<RenameParams>);
    }
}

/**
 * SignedURLParams 签名 URL 参数。
 */
export class SignedURLParams {
    "accountId": string;
    "bucket": string;
    "key": string;
    "domain"?: string;
    "deadlineSeconds"?: number;
    "https": boolean;

    /** Creates a new SignedURLParams instance. */
    constructor($$source: Partial<SignedURLParams> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("https" in $$source)) {
            this["https"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SignedURLParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SignedURLParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SignedURLParams($$parsedSource as Partial<SignedURLParams>);
    }
}

/**
 * TransferTask 表示上传/下载任务状态。
 */
export class TransferTask {
    "id": string;
    "type": string;
    "bucket": string;
    "key": string;
    "status": string;
    "progress": number;
    "errorMessage"?: string;
    "speed": number;
    "totalSize": number;
    "transferredSize": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new TransferTask instance. */
    constructor($$source: Partial<TransferTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("totalSize" in $$source)) {
            this["totalSize"] = 0;
        }
        if (!("transferredSize" in $$source)) {
            this["transferredSize"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferTask instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferTask($$parsedSource as Partial<TransferTask>);
    }
}

/**
 * UploadParams 上传参数。
 */
export class UploadParams {
    "accountId": string;
    "bucket": string;
    "key": string;
    "localPath"?: string;
    "sourceUrl"?: string;
    "overwrite": boolean;

    /** Creates a new UploadParams instance. */
    constructor($$source: Partial<UploadParams> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("overwrite" in $$source)) {
            this["overwrite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadParams($$parsedSource as Partial<UploadParams>);
    }
}

/**
 * VersionList 版本列表返回。
 */
export class VersionList {
    "versions": ObjectVersion[];
    "deleteMarkers"?: DeleteMarker[];
    "nextKeyMarker"?: string;
    "nextVersionMarker"?: string;
    "truncated": boolean;

    /** Creates a new VersionList instance. */
    constructor($$source: Partial<VersionList> = {}) {
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionList instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionList {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField0_0($$parsedSource["versions"]);
        }
        if ("deleteMarkers" in $$parsedSource) {
            $$parsedSource["deleteMarkers"] = $$createField1_0($$parsedSource["deleteMarkers"]);
        }
        return new VersionList($$parsedSource as Partial<VersionList>);
    }
}

/**
 * VersionListParams 版本列表查询参数。
 */
export class VersionListParams {
    "accountId": string;
    "bucket": string;
    "prefix": string;
    "keyMarker": string;
    "versionMarker": string;
    "limit": number;

    /** Creates a new VersionListParams instance. */
    constructor($$source: Partial<VersionListParams> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("keyMarker" in $$source)) {
            this["keyMarker"] = "";
        }
        if (!("versionMarker" in $$source)) {
            this["versionMarker"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionListParams instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionListParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionListParams($$parsedSource as Partial<VersionListParams>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = LifecycleTransition.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = ObjectItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ObjectVersion.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = DeleteMarker.createFrom;
const $$createType8 = $Create.Array($$createType7);
